### ISSUE TITLE
Football Crest Issue

### ISSUE THREAD

**Issue by ollyd10** [dfrt82/phplib-football-data#1]
When using the league table URL (http://api.football-data.org/v1/soccerseasons/398/leagueTable) i am having an issue getting a feedback from the crest within the league table section. I do not have a problem getting the images through teams section (http://api.football-data.org/v1/soccerseasons/398/teams) but this has a different ID name. Can someone please look at the issue of how i can get a return of an image for "crestURI" below.

{
    "leagueCaption": "Premier League 2015/16",
    "matchday": 10,
    "standing":
    [
        {
            "rank": 1,
            "team": "ManCity",
            "teamId": 65,
            "playedGames": 10,
            "crestURI": "http://upload.wikimedia.org/wikipedia/de/f/fd/ManCity.svg",
            "points": 22,
            "goals": 24,
            "goalsAgainst": 8,
            "goalDifference": 16
        },
]
}

This is not working for me: -

```
 $.ajax({
  headers: { 'X-Auth-Token': '(MYKEY)' },
  url: 'http://api.football-data.org/v1/soccerseasons/398/leagueTable',
  dataType: 'json',
  type: 'GET',
}).done(function(response) {
    var ul=document.querySelector("#result");
    var output="<tr><th></th><th>Team</th><th>P</th><th>GD</th><th>Pts</th></tr>";
    response.standing.forEach(function(team){
            output+="<img id='crest' src='"+team.crestURI+"'>"
    });
    ul.innerHTML=output;

});
```

**Comment by dfrt82** [comment]
I added the crestURI to the leagueTable resource as well, I guess this should solve your problem.
