### ISSUE TITLE
Couldn't get data for standings

### ISSUE THREAD

**Issue by McAtze** [dfrt82/phplib-football-data#11]
Hi,

i create a function called:
`public function findStandingsById($s) {
        $resource = 'competitions/' . $s . '/standings';
        $response = file_get_contents($this->baseUri . $resource, false, 
                                      stream_context_create($this->reqPrefs));
        return json_decode($response);
    }`

And add the the following code in the index.php but nothing happends. I got the "stage" but no standing. Where can i find the issue?

`<h3>Standings</h3>
                <table class="table table-striped">
                    <tr>
						<th>#</th>
						<th colspan="2">Name</th>
						<th>Matches</th>
						<th>W</th>
						<th>D</th>
						<th>L</th>
						<th>Goals</th>
						<th>GD</th>
						<th>Points</th>
                    </tr>
                    <?php foreach ($api->findStandingsById(2002)->standings as $standing) { ?>
                    <tr><td>
                    	<?php echo $standing->stage; ?>
                    </td></tr>
                    <tr>
                        <td><?php echo $standing->table->position; ?></td>
                        <td><?php echo $standing->table->team->crestUrl; ?></td>
                        <td><?php echo $standing->table->team->name; ?></td>
                        <td><?php echo $standing->table->playedGames; ?></td>
                        <td><?php echo $standing->table->won; ?></td>
                        <td><?php echo $standing->table->draw; ?></td>
                        <td><?php echo $standing->table->lost; ?></td>
                        <td><?php echo $standing->table->goalsFor; ?>:<?php echo $standing->table->goalsAgainst; ?></td>
                        <td><?php echo $standing->table->goalsDifference;  ?></td>
                        <td><?php echo $standing->table->points; ?></td>
                    </tr>
                    <?php } ?>
                </table>`

**Comment by McAtze** [comment]
@dfrt82 Could you say something about my question?

**Comment by dfrt82** [comment]
Unfortunately no as "nothing happens" is no error report I can give helpful information for.

**Comment by McAtze** [comment]
Hi,

there is no error in the logs. I just didn't get any data. I create a public function and want to get the standings data with an foreach loop. But i just get 3 empty rows..

![screenshot 2018-09-15 14 34 51](https://user-images.githubusercontent.com/8874582/45586302-d9c69000-b8f4-11e8-90de-a336558fdd0f.png)
![screenshot 2018-09-15 14 35 11](https://user-images.githubusercontent.com/8874582/45586303-d9c69000-b8f4-11e8-8f81-4b432848ce18.png)
![screenshot 2018-09-15 14 35 21](https://user-images.githubusercontent.com/8874582/45586304-da5f2680-b8f4-11e8-87d6-e1353ed246c5.png)

**Comment by McAtze** [comment]
@dfrt82 Did you support this git and could say something? I don't get the fault of my request.

All requests are post data, but the standings are show 3 empty rows.

**Comment by dfrt82** [comment]
Because there are 3 standings. Please check the example response of the API documentation or just var_dump your rows to find out the structure by yourself.

I updated the repo to have a function that properly outputs the total standing.
