### ISSUE TITLE
Get League Table

### ISSUE THREAD

**Issue by tmblog** [dfrt82/phplib-football-data#2]
In your example, it shows all fixtures past and present for a team, is it possible to get only future fixtures as allowed in the api.
$response = $api->getTeamById($searchQuery->teams[0]->id);
$fixtures = $response->getFixtures()->fixtures;

Thanks

**Comment by dfrt82** [comment]
How is this related to your headline, "Get League Table"?

However. I extended the function in the team model to be able to give it a second parameter "timeFrame". That will do what you're asking for.

Best,
daniel
